# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tinatra}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shota Fukumori (sora_h)"]
  s.date = %q{2010-09-14}
  s.description = %q{Ruby implemented DSL, designed for twitter bot.}
  s.email = %q{sora134@gmail.com}
  s.extra_rdoc_files = [
    "README.mkd"
  ]
  s.files = [
    "README.mkd",
     "Rakefile",
     "VERSION",
     "examples/simple.rb",
     "lib/tinatra.rb",
     "spec/helper_dummytter.rb",
     "spec/spec_tinatra.rb"
  ]
  s.homepage = %q{http://github.com/sorah/tinatra}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{DSL for twitter bot!}
  s.test_files = [
    "spec/helper_dummytter.rb",
     "spec/spec_tinatra.rb",
     "examples/simple.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubytter>, [">= 0"])
      s.add_runtime_dependency(%q<highline>, [">= 0"])
      s.add_runtime_dependency(%q<oauth>, [">= 0"])
    else
      s.add_dependency(%q<rubytter>, [">= 0"])
      s.add_dependency(%q<highline>, [">= 0"])
      s.add_dependency(%q<oauth>, [">= 0"])
    end
  else
    s.add_dependency(%q<rubytter>, [">= 0"])
    s.add_dependency(%q<highline>, [">= 0"])
    s.add_dependency(%q<oauth>, [">= 0"])
  end
end

